### ISSUE TITLE
uerID是什么，总是报这个错

### ISSUE THREAD

**Issue by Jamxscape** [xugy0926/daily-check-in#1]
userId must be a string.;at pages/event/event page addTodo function
Error: userId must be a string.

**Comment by antarts** [comment]
微信扫描登录即可。

**Comment by liulu1998** [comment]
> 

请问怎样操作？ 问题解决了吗？

**Comment by liulu1998** [comment]
> 微信扫描登录即可。

请问解决了吗 ？
